// <auto-generated />
using System;
using GeToque.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GeToque.Migrations
{
    [DbContext(typeof(GeToqueContext))]
    partial class GeToqueContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GeToque.Models.Confeccao", b =>
                {
                    b.Property<int>("ConfeccaoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Horario");

                    b.Property<int>("RoupaId");

                    b.HasKey("ConfeccaoId");

                    b.HasIndex("RoupaId");

                    b.ToTable("Confeccao");
                });

            modelBuilder.Entity("GeToque.Models.Roupa", b =>
                {
                    b.Property<int>("RoupaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Quantidade");

                    b.Property<int>("Tipos");

                    b.HasKey("RoupaId");

                    b.ToTable("Roupa");
                });

            modelBuilder.Entity("GeToque.Models.Confeccao", b =>
                {
                    b.HasOne("GeToque.Models.Roupa", "Roupa")
                        .WithMany()
                        .HasForeignKey("RoupaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
